FROM ubuntu:24.04

# Install dependencies and ibnetdiscover
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        infiniband-diags ibutils \
        && apt-get clean \
        && rm -rf /var/lib/apt/lists/*
