// Code generated by protoc-gen-go. DO NOT EDIT.
// source: topology.proto

package protos

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TopologyRequest struct {
	Provider             string   `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Region               string   `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	InstanceIds          []string `protobuf:"bytes,3,rep,name=instance_ids,json=instanceIds,proto3" json:"instance_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TopologyRequest) Reset()         { *m = TopologyRequest{} }
func (m *TopologyRequest) String() string { return proto.CompactTextString(m) }
func (*TopologyRequest) ProtoMessage()    {}
func (*TopologyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a326f5bb56fea2fc, []int{0}
}

func (m *TopologyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TopologyRequest.Unmarshal(m, b)
}
func (m *TopologyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TopologyRequest.Marshal(b, m, deterministic)
}
func (m *TopologyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TopologyRequest.Merge(m, src)
}
func (m *TopologyRequest) XXX_Size() int {
	return xxx_messageInfo_TopologyRequest.Size(m)
}
func (m *TopologyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TopologyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TopologyRequest proto.InternalMessageInfo

func (m *TopologyRequest) GetProvider() string {
	if m != nil {
		return m.Provider
	}
	return ""
}

func (m *TopologyRequest) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

func (m *TopologyRequest) GetInstanceIds() []string {
	if m != nil {
		return m.InstanceIds
	}
	return nil
}

type TopologyResponse struct {
	Instances            []*Instance `protobuf:"bytes,1,rep,name=instances,proto3" json:"instances,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *TopologyResponse) Reset()         { *m = TopologyResponse{} }
func (m *TopologyResponse) String() string { return proto.CompactTextString(m) }
func (*TopologyResponse) ProtoMessage()    {}
func (*TopologyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a326f5bb56fea2fc, []int{1}
}

func (m *TopologyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TopologyResponse.Unmarshal(m, b)
}
func (m *TopologyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TopologyResponse.Marshal(b, m, deterministic)
}
func (m *TopologyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TopologyResponse.Merge(m, src)
}
func (m *TopologyResponse) XXX_Size() int {
	return xxx_messageInfo_TopologyResponse.Size(m)
}
func (m *TopologyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TopologyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TopologyResponse proto.InternalMessageInfo

func (m *TopologyResponse) GetInstances() []*Instance {
	if m != nil {
		return m.Instances
	}
	return nil
}

type Instance struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	InstanceType         string   `protobuf:"bytes,2,opt,name=instance_type,json=instanceType,proto3" json:"instance_type,omitempty"`
	Provider             string   `protobuf:"bytes,3,opt,name=provider,proto3" json:"provider,omitempty"`
	Region               string   `protobuf:"bytes,4,opt,name=region,proto3" json:"region,omitempty"`
	DataCenter           string   `protobuf:"bytes,5,opt,name=data_center,json=dataCenter,proto3" json:"data_center,omitempty"`
	NetworkLayers        []string `protobuf:"bytes,6,rep,name=network_layers,json=networkLayers,proto3" json:"network_layers,omitempty"`
	NvlinkDomain         string   `protobuf:"bytes,7,opt,name=nvlink_domain,json=nvlinkDomain,proto3" json:"nvlink_domain,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Instance) Reset()         { *m = Instance{} }
func (m *Instance) String() string { return proto.CompactTextString(m) }
func (*Instance) ProtoMessage()    {}
func (*Instance) Descriptor() ([]byte, []int) {
	return fileDescriptor_a326f5bb56fea2fc, []int{2}
}

func (m *Instance) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Instance.Unmarshal(m, b)
}
func (m *Instance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Instance.Marshal(b, m, deterministic)
}
func (m *Instance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Instance.Merge(m, src)
}
func (m *Instance) XXX_Size() int {
	return xxx_messageInfo_Instance.Size(m)
}
func (m *Instance) XXX_DiscardUnknown() {
	xxx_messageInfo_Instance.DiscardUnknown(m)
}

var xxx_messageInfo_Instance proto.InternalMessageInfo

func (m *Instance) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Instance) GetInstanceType() string {
	if m != nil {
		return m.InstanceType
	}
	return ""
}

func (m *Instance) GetProvider() string {
	if m != nil {
		return m.Provider
	}
	return ""
}

func (m *Instance) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

func (m *Instance) GetDataCenter() string {
	if m != nil {
		return m.DataCenter
	}
	return ""
}

func (m *Instance) GetNetworkLayers() []string {
	if m != nil {
		return m.NetworkLayers
	}
	return nil
}

func (m *Instance) GetNvlinkDomain() string {
	if m != nil {
		return m.NvlinkDomain
	}
	return ""
}

func init() {
	proto.RegisterType((*TopologyRequest)(nil), "topology.TopologyRequest")
	proto.RegisterType((*TopologyResponse)(nil), "topology.TopologyResponse")
	proto.RegisterType((*Instance)(nil), "topology.Instance")
}

func init() {
	proto.RegisterFile("topology.proto", fileDescriptor_a326f5bb56fea2fc)
}

var fileDescriptor_a326f5bb56fea2fc = []byte{
	// 319 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0x41, 0x4f, 0xf2, 0x40,
	0x10, 0x86, 0xbf, 0xd2, 0x4f, 0xa4, 0x53, 0x41, 0xb2, 0x07, 0xb3, 0x72, 0x11, 0x6b, 0x4c, 0x38,
	0xa1, 0xc1, 0xa3, 0x37, 0xe5, 0x42, 0xf4, 0x54, 0x39, 0x79, 0xb0, 0x29, 0xdd, 0x09, 0x6e, 0xc0,
	0xdd, 0x75, 0x77, 0xc5, 0xf4, 0xdf, 0xfa, 0x53, 0x0c, 0xcb, 0xb6, 0x0d, 0x46, 0x4f, 0xed, 0x3c,
	0xef, 0x24, 0x7d, 0x66, 0xa6, 0xd0, 0xb3, 0x52, 0xc9, 0xb5, 0x5c, 0x96, 0x63, 0xa5, 0xa5, 0x95,
	0xa4, 0x53, 0xd5, 0xc9, 0x2b, 0x1c, 0xcf, 0xfd, 0x7b, 0x8a, 0xef, 0x1f, 0x68, 0x2c, 0x19, 0x40,
	0x47, 0x69, 0xb9, 0xe1, 0x0c, 0x35, 0x0d, 0x86, 0xc1, 0x28, 0x4a, 0xeb, 0x9a, 0x9c, 0x40, 0x5b,
	0xe3, 0x92, 0x4b, 0x41, 0x5b, 0x2e, 0xf1, 0x15, 0x39, 0x87, 0x23, 0x2e, 0x8c, 0xcd, 0x45, 0x81,
	0x19, 0x67, 0x86, 0x86, 0xc3, 0x70, 0x14, 0xa5, 0x71, 0xc5, 0x66, 0xcc, 0x24, 0x53, 0xe8, 0x37,
	0x5f, 0x32, 0x4a, 0x0a, 0x83, 0xe4, 0x1a, 0xa2, 0xaa, 0xc5, 0xd0, 0x60, 0x18, 0x8e, 0xe2, 0x09,
	0x19, 0xd7, 0xae, 0x33, 0x1f, 0xa5, 0x4d, 0x53, 0xf2, 0x15, 0x40, 0xa7, 0xe2, 0xa4, 0x07, 0x2d,
	0xce, 0xbc, 0x63, 0x8b, 0x33, 0x72, 0x01, 0xdd, 0xda, 0xc2, 0x96, 0x0a, 0xbd, 0x64, 0xad, 0x36,
	0x2f, 0x15, 0xee, 0x8d, 0x17, 0xfe, 0x39, 0xde, 0xff, 0xbd, 0xf1, 0xce, 0x20, 0x66, 0xb9, 0xcd,
	0xb3, 0x02, 0x85, 0x45, 0x4d, 0x0f, 0x5c, 0x08, 0x5b, 0x74, 0xef, 0x08, 0xb9, 0x84, 0x9e, 0x40,
	0xfb, 0x29, 0xf5, 0x2a, 0x5b, 0xe7, 0x25, 0x6a, 0x43, 0xdb, 0x6e, 0x03, 0x5d, 0x4f, 0x1f, 0x1d,
	0xdc, 0x0a, 0x8a, 0xcd, 0x9a, 0x8b, 0x55, 0xc6, 0xe4, 0x5b, 0xce, 0x05, 0x3d, 0xdc, 0x09, 0xee,
	0xe0, 0xd4, 0xb1, 0xc9, 0x4b, 0x73, 0x92, 0x27, 0xd4, 0x1b, 0x5e, 0x20, 0x79, 0x80, 0xfe, 0x14,
	0x4d, 0xa1, 0xf9, 0x02, 0xab, 0x88, 0x9c, 0x36, 0x8b, 0xfa, 0x71, 0xc1, 0xc1, 0xe0, 0xb7, 0x68,
	0xb7, 0xf2, 0xe4, 0xdf, 0x5d, 0xfc, 0x1c, 0x8d, 0xaf, 0x6e, 0xdd, 0x8f, 0x60, 0x16, 0x6d, 0xf7,
	0xbc, 0xf9, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x8e, 0xc6, 0xe8, 0x6b, 0x22, 0x02, 0x00, 0x00,
}
