# serving topograph endpoint
http:
  port: 49021
  ssl: false

# Set provider and engine for topograph to use
# provider: "test"
# engine: "test"

# waiting period before processing a request
request_aggregation_delay: 15s

# URL of an external gRPC service for request processing (optional)
# forward_service_url:

# number of results per API call (optional)
page_size: 100

# ssl credentials for when http.ssl = true
ssl:
  cert: /etc/topograph/ssl/server-cert.pem
  key: /etc/topograph/ssl/server-key.pem
  ca_cert: /etc/topograph/ssl/ca-cert.pem

# filepath to CSP credentials (optional)
# credentials_path:

# additional environment variables (optional)
env:
#  SLURM_CONF: /etc/slurm/slurm.conf
#  PATH:
