{{ include "topograph.validation" . }}
{{- $providerParams := default dict .Values.global.provider.params }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "topograph.fullname" . }}
  labels:
    {{- include "topograph.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "topograph.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "topograph.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "topograph.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /usr/local/bin/topograph
          args:
            - -v={{ .Values.verbosity }}
            {{- range $key, $value := .Values.topologyNodeLabels }}
            - -k8s-topology-key-{{ $key }}={{ $value }}
            {{- end }}
          env:
            - name: NODE_DATA_BROKER_NAME
              value: {{ printf "%s-%s" .Release.Name "node-data-broker" | trunc 63 | trimSuffix "-" }}
            - name: NODE_DATA_BROKER_NAMESPACE
              value: {{ .Release.Namespace }}
            {{- if eq .Values.global.provider.name "gcp" }}
            {{- if $providerParams.serviceAccountKeysSecret }}
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /etc/topograph/gcp/service-account-keys.json
            {{- else if $providerParams.workloadIdentityFederation }}
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /etc/topograph/gcp/credentials-config.json
            {{- end }}
            {{- end }}
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.global.service.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config-volume
              mountPath: /etc/topograph
          {{- if .Values.config.credentialsSecret }}
            - name: credentials
              mountPath: /etc/topograph/credentials
              readOnly: true
          {{- end }}
          {{- if eq .Values.global.provider.name "gcp" }}
          {{- if $providerParams.serviceAccountKeysSecret }}
            - name: service-account-keys
              mountPath: /etc/topograph/gcp/service-account-keys.json
              readOnly: true
          {{- else if $providerParams.workloadIdentityFederation }}
            - name: credentials-config
              mountPath: /etc/topograph/gcp
              readOnly: true
            - name: token
              mountPath: "/var/run/service-account"
              readOnly: true
          {{- end }}
          {{- end }}
          {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: config-volume
          configMap:
            defaultMode: 420
            name: {{ include "topograph.fullname" . }}
      {{- if .Values.config.credentialsSecret }}
        - name: credentials
          secret:
            secretName: {{ .Values.config.credentialsSecret }}
      {{- end }}
      {{- if eq .Values.global.provider.name "gcp" }}
      {{- if $providerParams.serviceAccountKeysSecret }}
        - name: service-account-keys
          secret:
            secretName: {{ $providerParams.serviceAccountKeysSecret }}
      {{- else if $providerParams.workloadIdentityFederation }}
        - name: credentials-config
          configMap:
            name: {{ $providerParams.workloadIdentityFederation.credentialsConfigmap }}
        - name: token
          projected:
            sources:
            - serviceAccountToken:
                audience: {{ $providerParams.workloadIdentityFederation.audience }}
                expirationSeconds: 3600
                path: token
      {{- end }}
      {{- end }}
      {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
