# Default values for topology-generator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  # provider: "aws", "oci", "gcp", "nebius", "netq", "baremetal" or "test".
  provider: aws
  #  engine: "k8s" or "slinky"
  engine: slinky
  engineParams:
    namespace: slurm
    podSelector:
      matchLabels:
        app.kubernetes.io/component: compute
    topologies:
      topo1:
        plugin: topology/block
        block_sizes: [2,4]
      topo2:
        plugin: topology/block
        block_sizes: [8,16]
      topo3:
        plugin: topology/tree
      topo-default:
        plugin: topology/flat
        cluster_default: true
    topology_config_path: topology.conf
    topology_configmap_name: slurm-config

nodeSelector:
  dedicated: user-workload

tolerations:
  - operator: Exists

node-observer:
  nodeSelector:
    dedicated: user-workload
  topograph:
    trigger:
      podSelector:
        matchLabels:
          app.kubernetes.io/component: compute
