global:
  provider:
    name: infiniband-k8s
    params:
      useGpuCliqueLabel: true
  engine:
    name: k8s

node-observer:
  topograph:
    trigger:
      nodeSelector:
        nvidia.com/gpu.present: "true"

node-data-broker:
  securityContext:
    privileged: true
  nodeSelector:
    nvidia.com/gpu.present: "true"
  volumeMounts:
  - name: sys-class-volume
    mountPath: /sys/class
  volumes:
  - name: sys-class-volume
    hostPath:
      path: /sys/class
      type: Directory
