name: Release Helm Charts

on: workflow_dispatch

jobs:
  release:
    runs-on: linux-amd64-cpu8

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.14.0

      - name: Package Helm chart
        run: |
          mkdir -p packaged
          helm lint charts/topograph
          helm package charts/topograph --destination packaged

      - name: Fetch existing Helm repo index
        run: |
          git fetch origin gh-pages || true
          git checkout origin/gh-pages -- index.yaml || true

      - name: Generate Helm repo index
        run: |
          if [ -f index.yaml ]; then
            helm repo index packaged --url https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }} --merge index.yaml
          else
            helm repo index packaged --url https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}
          fi

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./packaged
          publish_branch: gh-pages
          keep_files: true
