provider:
  name: dra
  params:
    nodeSelector:
      kwok.x-k8s.io/node: "fake"
engine:
  name: slinky
  params:
    namespace: slurm
    nodeSelector:
      kwok.x-k8s.io/node: "fake"
    podSelector:
      matchLabels:
        app.kubernetes.io/component: worker
    plugin: topology/block
    blockSizes: [8, 16, 32]
    useGpuCliqueLabel: true
    topologyConfigPath: topology.conf
    topologyConfigmapName: slurm-config-extra
    useDynamicNodes: true

config:
  requestAggregationDelay: 2s

nodeSelector:
  node-role.kubernetes.io/control-plane: ""

nodeObserver:
  nodeSelector:
    node-role.kubernetes.io/control-plane: ""
  topograph:
    trigger:
      nodeSelector:
        kwok.x-k8s.io/node: "fake"

nodeDataBroker:
  enabled: false
